### ISSUE TITLE
Spam command

### ISSUE THREAD

**Issue by mahdishahidi1** [chocochaos/GMGenie#1]
This addon will spam .ticket related all times
how can i turn it off?
i dont wana even check those tickets :(

**Comment by chocochaos** [comment]
Hello,

If you don't want to load tickets, you can remove this line from Tickets.lua
<https://github.com/chocochaos/GMGenie/blob/master/Tickets.lua>:

Chronos.scheduleRepeating('ticketrefresh', 60, GMGenie.Tickets.refresh);

It won't periodically check for new tickets anymore then.

Regards,

chocochaos

**Comment by mahdishahidi1** [comment]
Thanks :)
Now this wont check every time.
Now just when the game loads this addon will check, How can i remove this one?
(.ticket onlinelist)

**Comment by chocochaos** [comment]
Remove the line directly below that:
